### ISSUE TITLE
[REQUEST] Please upgrade to either current or LTR version

### ISSUE THREAD

**Issue by pcav** [onthelink-nl/scripts#3]
obj says it all

**Comment by MishaOpstal** [comment]
the actual package that the script uses to install QGIS depends on the package that is located on Flathub, when they update the package the script will install the newer version, like we said the script doesn't contain QGIS and we depend on Flatpak.....

We'll have to wait untill they update to a newer version, when they do everything should work fine

**Comment by pcav** [comment]
Got it, thanks.
Could you please open a ticket upstream then?

**Comment by MishaOpstal** [comment]
how do i open a ticket upstream (sry im still new to github)

**Comment by pcav** [comment]
Please have a look to the flatpack qgis project, they will certainly have a bugtracker.
Thanks.

**Comment by MishaOpstal** [comment]
oh yeah i will do that in a few weeks,
sorry but i first need to find a way to install older versions on flatpak, i also got request for specific version through mail so when that part is done i will try to contact flatpak for updating the QGIS package

**Comment by pcav** [comment]
Please have a look to the flatpack qgis project, they will certainly have a bugtracker.
Thanks.
