### ISSUE TITLE
[BUG] Improve install instructions

### ISSUE THREAD

**Issue by pcav** [onthelink-nl/scripts#4]
The script will work only on Linux enable Chromebooks. This is not clearly stated in the README

**Comment by MishaOpstal** [comment]
Is this README a better one? or would you prefer something else?

**Comment by pcav** [comment]
I think complete install instructions should go either in the README (please take not of the formatting, now broken) or in a dedicated INSTALL file.

**Comment by MishaOpstal** [comment]
i'll create an INSTALL_QGIS file that contains a link to the pdf (because the qgis script wont be the only one we will create...)
