### ISSUE TITLE
[BUG] Uninstall unclean

### ISSUE THREAD

**Issue by pcav** [onthelink-nl/scripts#5]
The uninstall procedure leaves much software on the machine.

**Comment by MishaOpstal** [comment]
I'll look into it right now

**Comment by MishaOpstal** [comment]
i tried to make the uninstall better, but im not home right now so i can't check everything,
i'll check every package flatpak installs and add them to the uninstaller

**Comment by MishaOpstal** [comment]
We tried to make the uninstall a whole lot better and we think we have found all packages, it may take github some time to update but i think it should be ready to go

**Comment by MishaOpstal** [comment]
if you find any leftovers of the files after removal please tell us because then we can add those directories to the removal too!

**Comment by MishaOpstal** [comment]
this issue will be fixed on the next update, if you think it's still unclean please report it to us again because when the new update comes out we will close this ticket for now

**Comment by MishaOpstal** [comment]
The new update just released, if you find anything wrong in the removal feature please reopen this ticket!!
